### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by Calinou** [martymcmodding/qUINT#21]
This repository appears to be under a proprietary license. Could you look into adding an [open source license](https://choosealicense.com/) to clear out usage and distribution rights, please? Right now, we're techncially not allowed to do anything with the code.

**Comment by martymcmodding** [comment]
qUINT used to have a CC license. Someone decided to use this against me (I released an additional file via Patreon and that made use of files with the CC license). Honest, obvious mistake on my end but instead of telling me, the person did everything to cause maximum damage to my income, linking it everywhere, creating other github repos with SEO descriptions and messaging game magazines to cover it, until it was 1st google result. It took a legal battle to settle this, money I will never see again. I don't believe in the FOSS spirit at all anyways, and I only open sourced the code by request and if that's what I get, then no FOSS licensing for my work ever again. If someone wants to ruin it for everyone, that's on them.

Also: the shaders are meant to be used with ReShade only, and it states clearly on [its homepage](www.reshade.me):

_Use preset files (*.ini) that can be created from ReShade's in-game user interface to share your configurations.
Do NOT share the binaries or shader files_

So you are not supposed to share the files with presets anyways, as the installer will fetch them for you. That's the intended use case and it's perfectly compatible with the current licensing.

**Comment by keybreak** [comment]
@martymcmodding 
That's very sad to hear...I had no idea.
In my personal opinion, you shouldn't just throw away good idea (FOSS), because of some purist jerk decided to act with war.
_______

Anyways, i've created couple of articles / threads on some Linux forums for gaming, speaking about future and great use in gaming of your qUINT and RTGI shader (which as far as i understood promised to be released as FOSS when it's ready).

I hope it's still true, coz:
1.This is a very big leap forward since forever, way more interesting than Nvidia's insane inefficient proprietary RTX...
2. My threads was heavily promoting your work and Patreon a lot of people got really excited about it (~10k views on each, since July 2020), so hopefully at least some of your legal battle will be covered by Patreon donations!

Good luck and keep up the great work you're doing, regardless :heart:
