### ISSUE TITLE
First-Person-View SSR BUG

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [martymcmodding/qUINT#6]
When you siting in a car and palying with the First-Person-View, the SSR won't work unless you make the car windows broken. I guess this is because SSR can't deal with the car window material right. Please fix this.

**Comment by martymcmodding** [comment]
With my ability of divination I see that you mean GTA V. No real way of knowing for sure since ReShade works for almost every game and you didn't mention anything besides the problem itself. Now SSR can only put reflections on data that is in the depth buffer, the default depth buffer of GTA V treats car windows as solid objects and doesn't contain the depth info of stuff outside the car if you're sitting in one. You can however use the options in the DX11 tab to switch to a different depth buffer that doesn't have this problem. All in all this is no issue of the shader itself and frankly unfixable on my side, its ReShade which is at fault here, or the user for not leveraging all features ReShade offers.
